version: '3'
services:
    app:
        build: ./docker-services/app
        image: seminariophp
        volumes:
            - ./slim:/var/www/html
        networks:
            - network
        ports:
            - "${APP_PORT}:80"
        command: php -S 0.0.0.0:80
        depends_on:
            composer:
                condition: service_completed_successfully
    composer:
        image: composer
        volumes:
            - ./slim:/app
        command: bash -c "([ -f composer.json ] && composer install -no) || exit 0"
    db:
        image: mysql:8.0
        command: ["--default-authentication-plugin=mysql_native_password"]
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: php
            MYSQL_USER: php
            MYSQL_PASSWORD: php
        volumes:
            - ./docker-services/db:/docker-entrypoint-initdb.d
        networks:
            - network
    dbadmin:
        image: phpmyadmin
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: php
            PMA_PASSWORD: php
        networks:
            - network
        ports:
            - "${DBADMIN_PORT}:80"
networks:
    network:
